os:
  - linux
  - osx
  - windows

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

sudo: enabled
language: cpp
compiler: g++

before_install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt update

    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    sudo apt-get install gcc-8 g++-8

    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60

    export CC=gcc-8
    export CXX=g++-8

    sudo apt-get install -y libx11-dev
    sudo apt-get install -y libcairo2-dev
    sudo apt-get install -y libsdl-pango-dev
    sudo apt-get install -y libglib2.0-dev
  fi

script:
  - cmake .
  - cmake --build .